name: 生成 README 置顶仓库卡片

on:
  schedule:
    - cron: "0 1 * * *" # Runs once daily at midnight
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: 检出仓库
        uses: actions/checkout@v7

      - name: 检出 stats-organization/github-readme-stats-action
        uses: actions/checkout@v7
        with:
          repository: stats-organization/github-readme-stats-action
          path: github-readme-stats-action
          ref: v2

      - name: 安装依赖
        run: |
          cd github-readme-stats-action
          npm install -g pnpm
          pnpm install --frozen-lockfile --prod --ignore-scripts

      - name: 生成卡片
        run: |
          mkdir -p img/repos
          cd github-readme-stats-action

          REPOS="
            mcdk
            cpython-builder
            libui-ng-windows-builder
            n2n-mingw64
            nginx-rtmp
            console-player
            all-of-resources
            mctoast
            mafish-extras
            SyFB_Strange
            CamMonitor_Server
          "

          for repo in "${REPOS[@]}"; do
            echo "==> 生成 img/repos/${repo}.svg ..."
            export INPUT_CARD="pin"
            export INPUT_OPTIONS="username=SystemFileB&repo=SystemFileB%2F${repo}&locale=cn&theme=transparent&show_icons=true&description_lines_count=3"
            export INPUT_PATH="../img/repos/${repo}.svg"
            export INPUT_CORE_VERSION="v2"
            export INPUT_FAIL_ON_ERROR="false"

            node index.js
          done

        env:
          PAT_1: ${{ secrets.GITHUB_TOKEN }}

      - name: 提交卡片
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add img/repos/*.svg
          git commit -m "更新 README 置顶仓库卡片" || exit 0
          git push


