name: 生成 README 其它卡片

on:
  schedule:
    - cron: "0 0 * * *" # Runs once daily at midnight
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: 检出仓库
        uses: actions/checkout@v7

      - name: 检出 stats-organization/github-readme-stats-action
        uses: actions/checkout@v7
        with:
          repository: stats-organization/github-readme-stats-action
          path: github-readme-stats-action
          ref: v2

      - name: 安装依赖
        run: |
          cd github-readme-stats-action
          npm install -g pnpm
          pnpm install --frozen-lockfile --prod --ignore-scripts

      - name: 生成卡片
        run: |
          mkdir -p img/repos
          cd github-readme-stats-action

          echo "==> 生成 img/stats.svg ..."
          export INPUT_CARD="stats"
          export INPUT_OPTIONS="username=SystemFileB&show_icons=true&theme=transparent&include_all_commits=true&locale=cn"
          export INPUT_PATH="../img/stats.svg"
          export INPUT_CORE_VERSION="v2"
          export INPUT_FAIL_ON_ERROR="false"

          node index.js

          echo "==> 生成 img/top-langs.svg ..."
          export INPUT_CARD="top-langs"
          export INPUT_OPTIONS="username=SystemFileB&layout=compact&theme=transparent&locale=cn&hide=markdown,xslt,html"
          export INPUT_PATH="../img/top-langs.svg"
          export INPUT_CORE_VERSION="v2"
          export INPUT_FAIL_ON_ERROR="false"

          node index.js

      - name: 提交卡片
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add img/*.svg
          git commit -m "更新 README 卡片" || exit 0
          git push
